---
title: "Bind_all_finaldataset"
author: "Marion Lieutaud"
date: "6/12/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE, 
                      tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

# Packages
```{r}
# packages
library(questionr)
library(expss)
library(tidyverse)
library(haven)
library(Hmisc)
library(foreign)
library(kableExtra)
```

# All new variables
```{r}
# migration history data
migration_history <- read_dta("~/Dropbox (Personal)/UKLHS Fellowship/UKLHS Migrant Lives Event History/migration_history.dta")

# citizenship data
citizenship <- read_dta("~/Dropbox (Personal)/UKLHS Fellowship/UKLHS Migrant Lives Event History/citizenship.dta")

# language and national identity data 
lang_natid <- read_dta("~/Dropbox (Personal)/UKLHS Fellowship/UKLHS Migrant Lives Event History/lang_natID.dta")

# reasons for migration and parents' work before migration
parentswork_reasonsmig <- read_dta("~/Dropbox (Personal)/UKLHS Fellowship/UKLHS Migrant Lives Event History/parentswork_reasonsmig.dta")
```
# Merge all for final dataset: migration_life
```{r}
migration_life <- migration_history %>%
  full_join(citizenship, by = "pidp") %>%
  full_join(lang_natid, by = "pidp") %>%
  full_join(parentswork_reasonsmig, by = "pidp")

View(migration_life)
```

# Write to dta
```{r}
# write to stata
write_dta(migration_life, 
          path = "migration_life.dta",
          label = attr(data, "label"))
```


